"""Xuhui healthy-route engine.

Public surface of the route package: pure-Python geodesy, the OSM road graph,
the ``optimize-xuhui-routes`` quality gates, the deterministic portfolio
generator and the artifact serialiser. Nothing in here reads the repository's
existing route data or calls any network service.
"""

from __future__ import annotations

from .areas import (
    AREA_DEFINITIONS,
    AREA_IDS,
    AreaDefinition,
    ResolvedArea,
    attach_nodes,
    nearest_area,
    resolve_areas,
)
from .gates import (
    RouteGateResult,
    RouteInput,
    duplicate_pairs,
    evaluate_portfolio,
    evaluate_route,
    same_mode_overlap,
    signature,
)
from .generator import (
    BANDS_KM,
    MODES,
    SEARCH_TOLERANCE,
    GeneratedRoute,
    Portfolio,
    band_targets,
    generate_portfolio,
    slot_plan,
)
from .geometry import (
    CRS_WGS84,
    Coord,
    CRSMismatchError,
    Ring,
    assert_crs,
    bbox,
    bearings_deg,
    circuity,
    endpoint_offset_m,
    haversine_m,
    in_district_ratio,
    isoperimetric_ratio,
    local_return_loops,
    overlap_ratio,
    point_in_ring,
    polyline_length_m,
    repeated_undirected_edges,
    retrace_segments,
    self_intersection_count,
    to_geojson_coords,
)
from .road_graph import (
    RoadGraph,
    build_graph,
    load_graph,
    node_key,
    prune_to_largest_component,
)
from .search import (
    FoundRoute,
    coords_from_edges,
    dijkstra,
    find_loop,
    make_route,
    pick_one_way,
    reconstruct,
)
from .simplify import douglas_peucker

__all__ = [
    "AREA_DEFINITIONS",
    "AREA_IDS",
    "BANDS_KM",
    "CRS_WGS84",
    "MODES",
    "SEARCH_TOLERANCE",
    "AreaDefinition",
    "CRSMismatchError",
    "Coord",
    "FoundRoute",
    "GeneratedRoute",
    "Portfolio",
    "ResolvedArea",
    "Ring",
    "RoadGraph",
    "RouteGateResult",
    "RouteInput",
    "assert_crs",
    "attach_nodes",
    "band_targets",
    "bbox",
    "bearings_deg",
    "build_graph",
    "circuity",
    "coords_from_edges",
    "dijkstra",
    "douglas_peucker",
    "duplicate_pairs",
    "endpoint_offset_m",
    "evaluate_portfolio",
    "evaluate_route",
    "find_loop",
    "generate_portfolio",
    "haversine_m",
    "in_district_ratio",
    "isoperimetric_ratio",
    "load_graph",
    "local_return_loops",
    "make_route",
    "nearest_area",
    "node_key",
    "overlap_ratio",
    "pick_one_way",
    "point_in_ring",
    "polyline_length_m",
    "prune_to_largest_component",
    "reconstruct",
    "repeated_undirected_edges",
    "resolve_areas",
    "retrace_segments",
    "same_mode_overlap",
    "self_intersection_count",
    "signature",
    "slot_plan",
    "to_geojson_coords",
]
